### ISSUE TITLE
getting the following error

### ISSUE THREAD

**Issue by amrsa1** [Hargne/jest-html-reporter#118]
im getting the following error after executing the test and jest reporter is not generating the report

```
internal/fs/utils.js:779
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of XMLElement
    at Object.writeFile (fs.js:1436:5)
    at /home/amrka/Desktop/__tests__/node_modules/jest-html-reporter/dist/main.js:47:13
    at /home/amrka/Desktop/__tests__/node_modules/mkdirp/index.js:30:20
    at FSReqCallback.oncomplete (fs.js:171:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by Hargne** [comment]
Hi,

Is it possible to see the jest config?

**Comment by mickog** [comment]
I am seeing this same issue

jest config 
```
module.exports = {
  preset: 'ts-jest',
  reporters: ["default",
    ["jest-junit", { outputDirectory: "test-reports/" }],
    ["./node_modules/jest-html-reporter", {
      "pageTitle": "CDK Test Report",
      "includeFailureMsg": true,
      "includeConsoleLog": true
    }]],
  testEnvironment: 'node',
  coveragePathIgnorePatterns: [
    "__tests__/util",
  ],
  testPathIgnorePatterns: [
    "__tests__/util",
  ],
  coverageDirectory: "test-reports/",
};
```

**Comment by mickog** [comment]
I can confirm downgrading my node version from v14.16.1 to v12.16.1 resolved the issue. Possibility issue is caused by this https://github.com/nodejs/node/pull/31030
